name: Lint

# on: [push]
  # Trigger the workflow on push or pull request,
  # but only for the main branch
# on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
on:
  push:
    # Run against main branch only.
    branches: [main]
  pull_request:
    # Include events emitted on code change only.
    types: [opened, synchronize]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
